/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 03:20:45 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;
import org.traccar.protocol.TelicProtocol;
import org.traccar.protocol.TelicProtocolDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TelicProtocolDecoder_ESTest extends TelicProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TelicProtocol telicProtocol0 = new TelicProtocol();
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(".beforeAdd() has thrown an exception; not adding.", 1039);
      try { 
        telicProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TelicProtocol telicProtocol0 = new TelicProtocol();
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("BHPF9za.", 2340);
      try { 
        telicProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, telicProtocol0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.TelicProtocol cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.TelicProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TelicProtocol telicProtocol0 = new TelicProtocol();
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("", 1866);
      Object object0 = telicProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, "");
      assertNull(object0);
  }
}
