/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 00:26:37 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetSocketAddress;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteTelicProtocolDecoder_ESTest extends EvosuiteTelicProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TelicProtocol telicProtocol0 = new TelicProtocol();
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      try { 
        telicProtocolDecoder0.decode((Channel) null, (SocketAddress) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TelicProtocol telicProtocol0 = new TelicProtocol();
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      H02ProtocolEncoder h02ProtocolEncoder0 = new H02ProtocolEncoder();
      try { 
        telicProtocolDecoder0.decode((Channel) null, (SocketAddress) null, h02ProtocolEncoder0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.H02ProtocolEncoder cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.TelicProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TelicProtocol telicProtocol0 = new TelicProtocol();
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 581);
      Object object0 = telicProtocolDecoder0.decode((Channel) null, inetSocketAddress0, "");
      assertNull(object0);
  }
}
