/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 22:18:31 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetSocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;
import org.traccar.protocol.CguardProtocol;
import org.traccar.protocol.CguardProtocolDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CguardProtocolDecoder_ESTest extends CguardProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      CguardProtocol cguardProtocol0 = new CguardProtocol();
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("'N[", 0);
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder(cguardProtocol0);
      try { 
        cguardProtocolDecoder0.decode((Channel) null, inetSocketAddress0, "'N[");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.BaseProtocolDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test1()  throws Throwable  {
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder((CguardProtocol) null);
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("ID:a_yF6[", 351);
      try { 
        cguardProtocolDecoder0.decode((Channel) null, inetSocketAddress0, "ID:a_yF6[");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.BaseProtocolDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test2()  throws Throwable  {
      CguardProtocol cguardProtocol0 = new CguardProtocol();
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder(cguardProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(1);
      Object object0 = new Object();
      try { 
        cguardProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.CguardProtocolDecoder", e);
      }
  }
}
