/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 20:49:49 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteWatchProtocolDecoder_ESTest extends EvosuiteWatchProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder((WatchProtocol) null);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      SocketAddress socketAddress0 = mock(SocketAddress.class, new ViolatedAssumptionAnswer());
      try { 
        watchProtocolDecoder0.decode(channel0, socketAddress0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder((WatchProtocol) null);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      SocketAddress socketAddress0 = mock(SocketAddress.class, new ViolatedAssumptionAnswer());
      try { 
        watchProtocolDecoder0.decode(channel0, socketAddress0, socketAddress0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.evosuite.shaded.org.mockito.codegen.SocketAddress$MockitoMock$534863383 cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.WatchProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WatchProtocol watchProtocol0 = mock(WatchProtocol.class, new ViolatedAssumptionAnswer());
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      SocketAddress socketAddress0 = mock(SocketAddress.class, new ViolatedAssumptionAnswer());
      Object object0 = watchProtocolDecoder0.decode(channel0, socketAddress0, "sKsK");
      assertNull(object0);
  }
}
