/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 23:05:32 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteMeitrackProtocolDecoder_ESTest extends EvosuiteMeitrackProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MeitrackProtocol meitrackProtocol0 = mock(MeitrackProtocol.class, new ViolatedAssumptionAnswer());
      MeitrackProtocolDecoder meitrackProtocolDecoder0 = new MeitrackProtocolDecoder(meitrackProtocol0);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      try { 
        meitrackProtocolDecoder0.decode(channel0, (SocketAddress) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.MeitrackProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MeitrackProtocol meitrackProtocol0 = mock(MeitrackProtocol.class, new ViolatedAssumptionAnswer());
      MeitrackProtocolDecoder meitrackProtocolDecoder0 = new MeitrackProtocolDecoder(meitrackProtocol0);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      SocketAddress socketAddress0 = mock(SocketAddress.class, new ViolatedAssumptionAnswer());
      try { 
        meitrackProtocolDecoder0.decode(channel0, socketAddress0, socketAddress0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.evosuite.shaded.org.mockito.codegen.SocketAddress$MockitoMock$1064070362 cannot be cast to org.jboss.netty.buffer.ChannelBuffer
         //
         verifyException("org.traccar.protocol.MeitrackProtocolDecoder", e);
      }
  }
}
