/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 02:43:14 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.traccar.protocol.Gl200Protocol;
import org.traccar.protocol.Gl200TextProtocolDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Gl200TextProtocolDecoder_ESTest extends Gl200TextProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Gl200Protocol gl200Protocol0 = new Gl200Protocol();
      Gl200TextProtocolDecoder gl200TextProtocolDecoder0 = null;
      try {
        gl200TextProtocolDecoder0 = new Gl200TextProtocolDecoder(gl200Protocol0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.Gl200TextProtocolDecoder", e);
      }
  }
}
