/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 23:39:08 GMT 2024
 */

package edu.harvard.h2ms.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteUserDetailsServiceImpl_ESTest extends EvosuiteUserDetailsServiceImpl_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      UserDetailsServiceImpl userDetailsServiceImpl0 = new UserDetailsServiceImpl();
      // Undeclared exception!
      try { 
        userDetailsServiceImpl0.loadUserByUsername("f:jEW@");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.harvard.h2ms.service.UserDetailsServiceImpl", e);
      }
  }
}
