/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 00:34:12 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteWatchProtocolDecoder_ESTest extends EvosuiteWatchProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WatchProtocol watchProtocol0 = new WatchProtocol();
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      InetAddress inetAddress0 = MockInetAddress.getLocalHost();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(inetAddress0, 0);
      try { 
        watchProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WatchProtocol watchProtocol0 = new WatchProtocol();
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      InetAddress inetAddress0 = MockInetAddress.getLocalHost();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(inetAddress0, 817);
      try { 
        watchProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, watchProtocol0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.WatchProtocol cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.WatchProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WatchProtocol watchProtocol0 = new WatchProtocol();
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      InetAddress inetAddress0 = MockInetAddress.getLocalHost();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(inetAddress0, 0);
      Object object0 = watchProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, ";<Rl xjLPZ0/].6wI|:");
      assertNull(object0);
  }
}
