/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 20:41:20 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.channel.Channel;
import org.jboss.netty.channel.ChannelHandlerContext;
import org.jboss.netty.channel.ChannelStateEvent;
import org.jboss.netty.channel.ChildChannelStateEvent;
import org.jboss.netty.channel.ExceptionEvent;
import org.jboss.netty.channel.WriteCompletionEvent;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteH02FrameDecoder_ESTest extends EvosuiteH02FrameDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder((-759));
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChildChannelStateEvent childChannelStateEvent0 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelOpen(channelHandlerContext1, childChannelStateEvent0);
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext3 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChildChannelStateEvent childChannelStateEvent1 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelClosed(channelHandlerContext3, childChannelStateEvent1);
      ChildChannelStateEvent childChannelStateEvent2 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelOpen(channelHandlerContext2, childChannelStateEvent2);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn(null).when(channelBuffer0).getByte(anyInt());
      doReturn(0).when(channelBuffer0).readableBytes();
      doReturn(0).when(channelBuffer0).readerIndex();
      ChannelHandlerContext channelHandlerContext4 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext5 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelStateEvent channelStateEvent0 = mock(ChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.channelOpen(channelHandlerContext5, channelStateEvent0);
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)41, (byte)42).when(channelBuffer1).getByte(anyInt());
      doReturn(0).when(channelBuffer1).indexOf(anyInt() , anyInt() , any(byte.class));
      doReturn((ChannelBuffer) null).when(channelBuffer1).readBytes(anyInt());
      doReturn(65484, 65432).when(channelBuffer1).readableBytes();
      doReturn((-1), (-759), (-5036), (-313)).when(channelBuffer1).readerIndex();
      doReturn(0).when(channelBuffer1).writerIndex();
      h02FrameDecoder0.decode(channelHandlerContext4, channel1, channelBuffer1);
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer0);
      ChannelHandlerContext channelHandlerContext6 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel2 = mock(Channel.class, new ViolatedAssumptionAnswer());
      try { 
        h02FrameDecoder0.decode(channelHandlerContext6, channel2, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02FrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ExceptionEvent exceptionEvent0 = mock(ExceptionEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.exceptionCaught(channelHandlerContext1, exceptionEvent0);
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(channelBuffer0).toString();
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)36).when(channelBuffer1).getByte(anyInt());
      doReturn(channelBuffer0).when(channelBuffer1).readBytes(anyInt());
      doReturn(5).when(channelBuffer1).readableBytes();
      doReturn((-2311)).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer1);
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer2 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)36).when(channelBuffer2).getByte(anyInt());
      doReturn((ChannelBuffer) null).when(channelBuffer2).readBytes(anyInt());
      doReturn(121).when(channelBuffer2).readableBytes();
      doReturn(1024).when(channelBuffer2).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext2, channel1, channelBuffer2);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder((-759));
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelStateEvent channelStateEvent0 = mock(ChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.channelConnected(channelHandlerContext0, channelStateEvent0);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      WriteCompletionEvent writeCompletionEvent0 = mock(WriteCompletionEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.writeComplete(channelHandlerContext2, writeCompletionEvent0);
      ChildChannelStateEvent childChannelStateEvent0 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext3 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChildChannelStateEvent childChannelStateEvent1 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelOpen(channelHandlerContext3, childChannelStateEvent1);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)79).when(channelBuffer0).getByte(anyInt());
      doReturn((-759)).when(channelBuffer0).readableBytes();
      doReturn((-1)).when(channelBuffer0).readerIndex();
      ChannelHandlerContext channelHandlerContext4 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)88).when(channelBuffer1).getByte(anyInt());
      doReturn((-759)).when(channelBuffer1).readableBytes();
      doReturn((int)(byte)88).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext4, channel1, channelBuffer1);
      h02FrameDecoder0.decode(channelHandlerContext1, channel0, channelBuffer0);
      ChannelHandlerContext channelHandlerContext5 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel2 = mock(Channel.class, new ViolatedAssumptionAnswer());
      try { 
        h02FrameDecoder0.decode(channelHandlerContext5, channel2, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02FrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder((-759));
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelStateEvent channelStateEvent0 = mock(ChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.channelConnected(channelHandlerContext0, channelStateEvent0);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext3 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      WriteCompletionEvent writeCompletionEvent0 = mock(WriteCompletionEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.writeComplete(channelHandlerContext3, writeCompletionEvent0);
      ChildChannelStateEvent childChannelStateEvent0 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelOpen(channelHandlerContext2, childChannelStateEvent0);
      ChannelHandlerContext channelHandlerContext4 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChildChannelStateEvent childChannelStateEvent1 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelOpen(channelHandlerContext4, childChannelStateEvent1);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)79).when(channelBuffer0).getByte(anyInt());
      doReturn((-759)).when(channelBuffer0).readableBytes();
      doReturn((-1)).when(channelBuffer0).readerIndex();
      ChannelHandlerContext channelHandlerContext5 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)88).when(channelBuffer1).getByte(anyInt());
      doReturn((-759)).when(channelBuffer1).readableBytes();
      doReturn((int)(byte)88).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext5, channel1, channelBuffer1);
      h02FrameDecoder0.decode(channelHandlerContext1, channel0, channelBuffer0);
      ChannelHandlerContext channelHandlerContext6 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel2 = mock(Channel.class, new ViolatedAssumptionAnswer());
      try { 
        h02FrameDecoder0.decode(channelHandlerContext6, channel2, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02FrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ExceptionEvent exceptionEvent0 = mock(ExceptionEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.exceptionCaught(channelHandlerContext1, exceptionEvent0);
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(channelBuffer0).toString();
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)36).when(channelBuffer1).getByte(anyInt());
      doReturn(channelBuffer0).when(channelBuffer1).readBytes(anyInt());
      doReturn(5).when(channelBuffer1).readableBytes();
      doReturn((-2311)).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer1);
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer2 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte) (-20)).when(channelBuffer2).getByte(anyInt());
      doReturn((-207)).when(channelBuffer2).readableBytes();
      doReturn(372).when(channelBuffer2).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext2, channel1, channelBuffer2);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)1, (byte)1, (byte)0, (byte)92, (byte)92).when(channelBuffer0).getByte(anyInt());
      doReturn((int)(byte)1, (int)(byte)1, 2713, (int)(byte)0, 65535).when(channelBuffer0).readableBytes();
      doReturn(90, 2475, 1936, 1, (int)(byte)92).when(channelBuffer0).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ExceptionEvent exceptionEvent0 = mock(ExceptionEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.exceptionCaught(channelHandlerContext1, exceptionEvent0);
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)36).when(channelBuffer0).getByte(anyInt());
      doReturn((ChannelBuffer) null).when(channelBuffer0).readBytes(anyInt());
      doReturn(5).when(channelBuffer0).readableBytes();
      doReturn((-2311)).when(channelBuffer0).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer0);
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn(null).when(channelBuffer1).getByte(anyInt());
      doReturn(0).when(channelBuffer1).readableBytes();
      doReturn(0).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext2, channel1, channelBuffer1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(0);
      assertEquals(1024, h02FrameDecoder0.getMaxCumulationBufferComponents());
      
      h02FrameDecoder0.setUnfold(true);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)93).when(channelBuffer0).getByte(anyInt());
      doReturn(42, (int)(byte) (-128), (int)(byte)93, (-1583), (-1583)).when(channelBuffer0).readableBytes();
      doReturn(42).when(channelBuffer0).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer0);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel1 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn(null).when(channelBuffer1).getByte(anyInt());
      doReturn(0).when(channelBuffer1).readableBytes();
      doReturn(0).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext1, channel1, channelBuffer1);
      H02FrameDecoder h02FrameDecoder1 = new H02FrameDecoder((-697));
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel2 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer2 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn(null).when(channelBuffer2).getByte(anyInt());
      doReturn(0).when(channelBuffer2).readableBytes();
      doReturn(0).when(channelBuffer2).readerIndex();
      h02FrameDecoder1.decode(channelHandlerContext2, channel2, channelBuffer2);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5795);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)36).when(channelBuffer0).getByte(anyInt());
      doReturn((-263)).when(channelBuffer0).readableBytes();
      doReturn((-263)).when(channelBuffer0).readerIndex();
      H02FrameDecoder h02FrameDecoder1 = new H02FrameDecoder(5795);
      h02FrameDecoder1.decode(channelHandlerContext0, (Channel) null, channelBuffer0);
      H02FrameDecoder h02FrameDecoder2 = new H02FrameDecoder(5795);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn(null).when(channelBuffer1).getByte(anyInt());
      doReturn(0).when(channelBuffer1).readableBytes();
      doReturn(0).when(channelBuffer1).readerIndex();
      h02FrameDecoder2.decode(channelHandlerContext1, (Channel) null, channelBuffer1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5795);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)36).when(channelBuffer0).getByte(anyInt());
      doReturn((-263)).when(channelBuffer0).readableBytes();
      doReturn((-263)).when(channelBuffer0).readerIndex();
      H02FrameDecoder h02FrameDecoder1 = new H02FrameDecoder(5795);
      h02FrameDecoder1.decode(channelHandlerContext0, (Channel) null, channelBuffer0);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer1 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn(null).when(channelBuffer1).getByte(anyInt());
      doReturn(0).when(channelBuffer1).readableBytes();
      doReturn(0).when(channelBuffer1).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext1, (Channel) null, channelBuffer1);
      ChannelHandlerContext channelHandlerContext2 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      try { 
        h02FrameDecoder1.decode(channelHandlerContext2, (Channel) null, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02FrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int int0 = 42;
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(42);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.beforeAdd(channelHandlerContext0);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      byte byte0 = (byte)10;
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)10, null, null, null, null).when(channelBuffer0).getByte(anyInt());
      doReturn(1024, 0, 0, 0, 0).when(channelBuffer0).readableBytes();
      doReturn((-1892), 0, 0, 0, 0).when(channelBuffer0).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext1, channel0, channelBuffer0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(5);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte)1, null, null, null, null).when(channelBuffer0).getByte(anyInt());
      doReturn((int)(byte)1, 0, 0, 0, 0).when(channelBuffer0).readableBytes();
      doReturn(90, 0, 0, 0, 0).when(channelBuffer0).readerIndex();
      h02FrameDecoder0.decode(channelHandlerContext0, channel0, channelBuffer0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(255);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      doReturn((byte) (-6)).when(channelBuffer0).getByte(anyInt());
      doReturn(0).when(channelBuffer0).readableBytes();
      doReturn(255).when(channelBuffer0).readerIndex();
      h02FrameDecoder0.decode((ChannelHandlerContext) null, channel0, channelBuffer0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(0);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.channelConnected(channelHandlerContext0, (ChannelStateEvent) null);
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder((-622));
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      ChildChannelStateEvent childChannelStateEvent0 = mock(ChildChannelStateEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.childChannelOpen(channelHandlerContext1, childChannelStateEvent0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(1434);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(0);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelBuffer channelBuffer0 = mock(ChannelBuffer.class, new ViolatedAssumptionAnswer());
      try { 
        h02FrameDecoder0.decode(channelHandlerContext0, channel0, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02FrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int int0 = 0;
      H02FrameDecoder h02FrameDecoder0 = new H02FrameDecoder(0);
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      ChannelHandlerContext channelHandlerContext1 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      WriteCompletionEvent writeCompletionEvent0 = mock(WriteCompletionEvent.class, new ViolatedAssumptionAnswer());
      h02FrameDecoder0.writeComplete(channelHandlerContext1, writeCompletionEvent0);
      ChannelBuffer channelBuffer0 = null;
      try { 
        h02FrameDecoder0.decode(channelHandlerContext0, channel0, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02FrameDecoder", e);
      }
  }
}
