/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 00:41:51 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteOrder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.buffer.HeapChannelBufferFactory;
import org.jboss.netty.buffer.LittleEndianHeapChannelBuffer;
import org.jboss.netty.buffer.TruncatedChannelBuffer;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteWondexProtocolDecoder_ESTest extends EvosuiteWondexProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      WondexProtocol wondexProtocol0 = new WondexProtocol();
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder(wondexProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(0);
      try { 
        wondexProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.WondexProtocolDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test1()  throws Throwable  {
      WondexProtocol wondexProtocol0 = new WondexProtocol();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(0);
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder(wondexProtocol0);
      LittleEndianHeapChannelBuffer littleEndianHeapChannelBuffer0 = new LittleEndianHeapChannelBuffer(0);
      TruncatedChannelBuffer truncatedChannelBuffer0 = new TruncatedChannelBuffer(littleEndianHeapChannelBuffer0, 0);
      try { 
        wondexProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, truncatedChannelBuffer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Invalid index of 0, maximum is 0
         //
         verifyException("org.jboss.netty.buffer.TruncatedChannelBuffer", e);
      }
  }

  @Test(timeout = 50)
  public void test2()  throws Throwable  {
      WondexProtocol wondexProtocol0 = new WondexProtocol();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(0);
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder(wondexProtocol0);
      HeapChannelBufferFactory heapChannelBufferFactory0 = new HeapChannelBufferFactory();
      ByteOrder byteOrder0 = ByteOrder.nativeOrder();
      ChannelBuffer channelBuffer0 = heapChannelBufferFactory0.getBuffer(byteOrder0, 0);
      try { 
        wondexProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, channelBuffer0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.jboss.netty.buffer.HeapChannelBuffer", e);
      }
  }

  @Test(timeout = 50)
  public void test3()  throws Throwable  {
      WondexProtocol wondexProtocol0 = new WondexProtocol();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(0);
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder(wondexProtocol0);
      HeapChannelBufferFactory heapChannelBufferFactory0 = new HeapChannelBufferFactory();
      ByteOrder byteOrder0 = ByteOrder.BIG_ENDIAN;
      ChannelBuffer channelBuffer0 = heapChannelBufferFactory0.getBuffer(byteOrder0, 3176);
      TruncatedChannelBuffer truncatedChannelBuffer0 = new TruncatedChannelBuffer(channelBuffer0, 2683);
      Object object0 = wondexProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, truncatedChannelBuffer0);
      assertNull(object0);
  }

  @Test(timeout = 50)
  public void test4()  throws Throwable  {
      WondexProtocol wondexProtocol0 = new WondexProtocol();
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder(wondexProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(0);
      try { 
        wondexProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, mockInetSocketAddress0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.evosuite.runtime.mock.java.net.MockInetSocketAddress cannot be cast to org.jboss.netty.buffer.ChannelBuffer
         //
         verifyException("org.traccar.protocol.WondexProtocolDecoder", e);
      }
  }
}
