/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 03 00:31:34 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteCguardProtocolDecoder_ESTest extends EvosuiteCguardProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CguardProtocol cguardProtocol0 = new CguardProtocol();
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder(cguardProtocol0);
      try { 
        cguardProtocolDecoder0.decode((Channel) null, (SocketAddress) null, cguardProtocol0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.CguardProtocol cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.CguardProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CguardProtocol cguardProtocol0 = new CguardProtocol();
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder(cguardProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("IDRO:&qSwe]&#/91L", 2966);
      try { 
        cguardProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, "IDRO:&qSwe]&#/91L");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.BaseProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CguardProtocol cguardProtocol0 = new CguardProtocol();
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder(cguardProtocol0);
      try { 
        cguardProtocolDecoder0.decode((Channel) null, (SocketAddress) null, "ID:");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.BaseProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CguardProtocolDecoder cguardProtocolDecoder0 = new CguardProtocolDecoder((CguardProtocol) null);
      try { 
        cguardProtocolDecoder0.decode((Channel) null, (SocketAddress) null, "(dd)(dd)(dd):");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.BaseProtocolDecoder", e);
      }
  }
}
