/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 20:44:12 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteTelicProtocolDecoder_ESTest extends EvosuiteTelicProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder((TelicProtocol) null);
      try { 
        telicProtocolDecoder0.decode((Channel) null, (SocketAddress) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 50)
  public void test1()  throws Throwable  {
      TelicProtocol telicProtocol0 = mock(TelicProtocol.class, new ViolatedAssumptionAnswer());
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder(telicProtocol0);
      Channel channel0 = mock(Channel.class, new ViolatedAssumptionAnswer());
      SocketAddress socketAddress0 = mock(SocketAddress.class, new ViolatedAssumptionAnswer());
      try { 
        telicProtocolDecoder0.decode(channel0, socketAddress0, channel0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jboss.netty.channel.Channel$MockitoMock$138170926 cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.TelicProtocolDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test2()  throws Throwable  {
      TelicProtocolDecoder telicProtocolDecoder0 = new TelicProtocolDecoder((TelicProtocol) null);
      Object object0 = telicProtocolDecoder0.decode((Channel) null, (SocketAddress) null, "9HB(w]0b!-OSLt7V*");
      assertNull(object0);
  }
}
