/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 20:58:07 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteWondexProtocolDecoder_ESTest extends EvosuiteWondexProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder((WondexProtocol) null);
      try { 
        wondexProtocolDecoder0.decode((Channel) null, (SocketAddress) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.WondexProtocolDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test1()  throws Throwable  {
      WondexProtocolDecoder wondexProtocolDecoder0 = new WondexProtocolDecoder((WondexProtocol) null);
      try { 
        wondexProtocolDecoder0.decode((Channel) null, (SocketAddress) null, wondexProtocolDecoder0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.WondexProtocolDecoder cannot be cast to org.jboss.netty.buffer.ChannelBuffer
         //
         verifyException("org.traccar.protocol.WondexProtocolDecoder", e);
      }
  }
}
