/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 03:09:23 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;
import org.traccar.protocol.WatchProtocol;
import org.traccar.protocol.WatchProtocolDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WatchProtocolDecoder_ESTest extends WatchProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      WatchProtocol watchProtocol0 = new WatchProtocol();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(584);
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      try { 
        watchProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 50)
  public void test1()  throws Throwable  {
      WatchProtocol watchProtocol0 = new WatchProtocol();
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(4);
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      try { 
        watchProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, watchProtocol0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.WatchProtocol cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.WatchProtocolDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test2()  throws Throwable  {
      WatchProtocol watchProtocol0 = new WatchProtocol();
      WatchProtocolDecoder watchProtocolDecoder0 = new WatchProtocolDecoder(watchProtocol0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(1617);
      Object object0 = watchProtocolDecoder0.decode((Channel) null, mockInetSocketAddress0, "TV+#]b4\"Q<NLl34&s+a");
      assertNull(object0);
  }
}
