/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 13:48:08 GMT 2024
 */

package edu.harvard.h2ms.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.harvard.h2ms.service.UserDetailsServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserDetailsServiceImpl_ESTest extends UserDetailsServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserDetailsServiceImpl userDetailsServiceImpl0 = new UserDetailsServiceImpl();
      // Undeclared exception!
      try { 
        userDetailsServiceImpl0.loadUserByUsername("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.harvard.h2ms.service.UserDetailsServiceImpl", e);
      }
  }
}
