/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 23:25:14 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.buffer.BigEndianHeapChannelBuffer;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.buffer.LittleEndianHeapChannelBuffer;
import org.jboss.netty.channel.Channel;
import org.jboss.netty.channel.ChannelHandlerContext;
import org.jboss.netty.channel.DefaultChannelPipeline;
import org.jboss.netty.channel.local.DefaultLocalClientChannelFactory;
import org.jboss.netty.channel.local.LocalChannel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteTotemFrameDecoder_ESTest extends EvosuiteTotemFrameDecoder_ESTest_scaffolding {

  @Test(timeout = 50)
  public void test0()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      DefaultLocalClientChannelFactory defaultLocalClientChannelFactory0 = new DefaultLocalClientChannelFactory();
      LocalChannel localChannel0 = defaultLocalClientChannelFactory0.newChannel(defaultChannelPipeline0);
      byte[] byteArray0 = new byte[10];
      BigEndianHeapChannelBuffer bigEndianHeapChannelBuffer0 = new BigEndianHeapChannelBuffer(byteArray0);
      totemFrameDecoder0.decode((ChannelHandlerContext) null, localChannel0, bigEndianHeapChannelBuffer0);
      //  // Unstable assertion: assertEquals(1, (int)localChannel0.getId());
  }

  @Test(timeout = 50)
  public void test1()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      DefaultLocalClientChannelFactory defaultLocalClientChannelFactory0 = new DefaultLocalClientChannelFactory();
      LocalChannel localChannel0 = defaultLocalClientChannelFactory0.newChannel(defaultChannelPipeline0);
      try { 
        totemFrameDecoder0.decode((ChannelHandlerContext) null, localChannel0, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.TotemFrameDecoder", e);
      }
  }

  @Test(timeout = 50)
  public void test2()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      LittleEndianHeapChannelBuffer littleEndianHeapChannelBuffer0 = new LittleEndianHeapChannelBuffer(1024);
      Object object0 = totemFrameDecoder0.decode((ChannelHandlerContext) null, (Channel) null, littleEndianHeapChannelBuffer0);
      assertNull(object0);
  }

  @Test(timeout = 50)
  public void test3()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      LittleEndianHeapChannelBuffer littleEndianHeapChannelBuffer0 = new LittleEndianHeapChannelBuffer(1024);
      ChannelBuffer channelBuffer0 = littleEndianHeapChannelBuffer0.readSlice(1024);
      Object object0 = totemFrameDecoder0.decode((ChannelHandlerContext) null, (Channel) null, channelBuffer0);
      assertNull(object0);
  }
}
