/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 03:25:04 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.buffer.DirectChannelBufferFactory;
import org.jboss.netty.buffer.LittleEndianHeapChannelBuffer;
import org.jboss.netty.channel.ChannelHandlerContext;
import org.jboss.netty.channel.DefaultChannelPipeline;
import org.jboss.netty.channel.local.DefaultLocalClientChannelFactory;
import org.jboss.netty.channel.local.DefaultLocalServerChannelFactory;
import org.jboss.netty.channel.local.LocalChannel;
import org.jboss.netty.channel.local.LocalServerChannel;
import org.junit.runner.RunWith;
import org.traccar.protocol.TotemFrameDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TotemFrameDecoder_ESTest extends TotemFrameDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      DefaultLocalServerChannelFactory defaultLocalServerChannelFactory0 = new DefaultLocalServerChannelFactory();
      LocalServerChannel localServerChannel0 = defaultLocalServerChannelFactory0.newChannel(defaultChannelPipeline0);
      DirectChannelBufferFactory directChannelBufferFactory0 = new DirectChannelBufferFactory(1024);
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(10);
      ChannelBuffer channelBuffer0 = directChannelBufferFactory0.getBuffer(byteBuffer0);
      totemFrameDecoder0.decode((ChannelHandlerContext) null, localServerChannel0, channelBuffer0);
      //  // Unstable assertion: assertEquals(20, (int)localServerChannel0.getId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      DefaultLocalServerChannelFactory defaultLocalServerChannelFactory0 = new DefaultLocalServerChannelFactory();
      LocalServerChannel localServerChannel0 = defaultLocalServerChannelFactory0.newChannel(defaultChannelPipeline0);
      DirectChannelBufferFactory directChannelBufferFactory0 = new DirectChannelBufferFactory(65280);
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(65280);
      ChannelBuffer channelBuffer0 = directChannelBufferFactory0.getBuffer(byteBuffer0);
      totemFrameDecoder0.decode((ChannelHandlerContext) null, localServerChannel0, channelBuffer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      DefaultLocalServerChannelFactory defaultLocalServerChannelFactory0 = new DefaultLocalServerChannelFactory();
      LocalServerChannel localServerChannel0 = defaultLocalServerChannelFactory0.newChannel(defaultChannelPipeline0);
      try { 
        totemFrameDecoder0.decode((ChannelHandlerContext) null, localServerChannel0, (ChannelBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.TotemFrameDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TotemFrameDecoder totemFrameDecoder0 = new TotemFrameDecoder();
      DefaultLocalClientChannelFactory defaultLocalClientChannelFactory0 = new DefaultLocalClientChannelFactory();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      LocalChannel localChannel0 = defaultLocalClientChannelFactory0.newChannel(defaultChannelPipeline0);
      LittleEndianHeapChannelBuffer littleEndianHeapChannelBuffer0 = new LittleEndianHeapChannelBuffer(1024);
      totemFrameDecoder0.decode((ChannelHandlerContext) null, localChannel0, littleEndianHeapChannelBuffer0);
      assertEquals(0, (int)localChannel0.getId());
  }
}
