/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 01 03:07:03 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.buffer.DynamicChannelBuffer;
import org.jboss.netty.buffer.TruncatedChannelBuffer;
import org.jboss.netty.channel.Channel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteH02ProtocolDecoder_ESTest extends EvosuiteH02ProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      H02Protocol h02Protocol0 = new H02Protocol();
      H02ProtocolDecoder h02ProtocolDecoder0 = new H02ProtocolDecoder(h02Protocol0);
      try { 
        h02ProtocolDecoder0.decode((Channel) null, (SocketAddress) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.H02ProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      H02Protocol h02Protocol0 = new H02Protocol();
      H02ProtocolDecoder h02ProtocolDecoder0 = new H02ProtocolDecoder(h02Protocol0);
      DynamicChannelBuffer dynamicChannelBuffer0 = new DynamicChannelBuffer(876);
      ChannelBuffer channelBuffer0 = dynamicChannelBuffer0.duplicate();
      TruncatedChannelBuffer truncatedChannelBuffer0 = new TruncatedChannelBuffer(channelBuffer0, 0);
      try { 
        h02ProtocolDecoder0.decode((Channel) null, (SocketAddress) null, truncatedChannelBuffer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Invalid index of 1, maximum is 0
         //
         verifyException("org.jboss.netty.buffer.TruncatedChannelBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      H02Protocol h02Protocol0 = new H02Protocol();
      H02ProtocolDecoder h02ProtocolDecoder0 = new H02ProtocolDecoder(h02Protocol0);
      try { 
        h02ProtocolDecoder0.decode((Channel) null, (SocketAddress) null, h02Protocol0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.traccar.protocol.H02Protocol cannot be cast to org.jboss.netty.buffer.ChannelBuffer
         //
         verifyException("org.traccar.protocol.H02ProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      H02Protocol h02Protocol0 = new H02Protocol();
      H02ProtocolDecoder h02ProtocolDecoder0 = new H02ProtocolDecoder(h02Protocol0);
      DynamicChannelBuffer dynamicChannelBuffer0 = new DynamicChannelBuffer(114);
      ChannelBuffer channelBuffer0 = dynamicChannelBuffer0.duplicate();
      TruncatedChannelBuffer truncatedChannelBuffer0 = new TruncatedChannelBuffer(channelBuffer0, 114);
      Object object0 = h02ProtocolDecoder0.decode((Channel) null, (SocketAddress) null, truncatedChannelBuffer0);
      assertNull(object0);
  }
}
